---
title: "Laboratorio #4"
output: html_document
---

```{r setup, include=FALSE}
library(leaflet)
library(raster)
library(rgdal)
library(sf)

cr_ara_ambiguus <-
  st_read(
    "https://raw.githubusercontent.com/geoprocesamiento-2020i/datos/master/biodiversidad/registros-presencia/cr/cr-ara-ambiguus.geojson"
  )
cr_pharo_mocinno <-
  st_read(
    "https://raw.githubusercontent.com/geoprocesamiento-2020i/datos/master/biodiversidad/registros-presencia/cr/cr_pharomachrus_mocinno.geojson"
  )

altitude <- getData("worldclim", var="alt", res=.5, lon=-84, lat=10)
cr_altitude <- crop(altitude, extent(-86, -82.3, 8, 11.3))  

precipitation <- getData("worldclim", var="bio", res=.5, lon=-84, lat=10)
precipitation <- precipitation[[c(12)]]
names(precipitation) <- c("Prec")
cr_precipitation <- crop(precipitation, extent(-86, -82.3, 8, 11.3))

pal <- colorNumeric(
  c("#0C2C84", "#41B6C4", "#FFFFCC"), 
  values(cr_altitude), 
  na.color = "transparent"
)

m <- leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addCircleMarkers(data = cr_ara_ambiguus,
                   stroke = F,
                   radius = 4,
                   fillColor = 'green',
                   fillOpacity = 1,
                   group = "Ara ambiguus",
                   popup = paste(cr_ara_ambiguus$locality, 
                                 cr_ara_ambiguus$year, 
                                 sep = '<br/>'
                   )
  ) %>%
   addCircleMarkers(data = cr_pharo_mocinno,
                   stroke = F,
                   radius = 4,
                   fillColor = 'red',
                   fillOpacity = 1,
                   group = "Pharomachrus mocinno",
                   popup = paste(cr_pharo_mocinno$locality, 
                                 cr_pharo_mocinno$year, 
                                 sep = '<br/>'
                   )
  ) %>%addRasterImage(cr_altitude, 
                 colors = pal, 
                 opacity = 0.8, 
                 group = "Altitud"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Altitud", "Ara ambiguus", "Pharomachrus mocinno"),
    options = layersControlOptions(collapsed = FALSE)    
  ) %>%
  addLegend(pal = pal, 
            values = values(cr_altitude), 
            title = "Altitud"
  ) %>%
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$Stamen.TonerLite
  )

```

```{r}
m
```